#! /bin/sh

# Init script for aesdsocket daemon
case $1 in
    start)
        start-stop-daemon -S -n aesdsocket -a /usr/bin/aesdsocket -- -d
        echo "Starting aesdsocket: OK"
        ;;
    stop)
        start-stop-daemon -K -n aesdsocket
        echo "Stopping aesdsocket: OK"
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
esac

exit 0

